import React, { useEffect } from "react";
import { useDispatch } from "react-redux";
import { setCurrentPage } from "../../redux/app";
import "./style.css";

export default function Terms(props) {
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(setCurrentPage("terms"));
  }, []);

  return (
    <div className="terms_container col-12 d-flex justify-content-center align-items-center">
      <div className="page_box col-8">
        <h1 style={{ color: "white", fontSize: "3rem" }}>Terms & Conditions</h1>
        <p style={{ color: "white", fontSize: "1.25rem", padding: "0px 40px" }}>
          NFTeePeeClub is a collection of digital artworks (NFTs) running on the
          Solana network. This website is only an interface allowing
          participants to exchange digital collectibles. Users are entirely
          responsible for the safety and management of their own private Solana
          wallets and validating all transactions and contracts generated by
          this website before approval. Furthermore, as the NFTeePeeClub smart
          contract runs on the Solana network, there is no ability to undo,
          reverse, or restore any transactions. This website and its connected
          services are provided “as is” and “as available” without warranty of
          any kind. By using this website you are accepting sole responsibility
          for any and all transactions involving NFTeePeeClub digital
          collectibles.
        </p>
        <hr
          style={{
            color: "white",
            width: "100%",
            justifySelf: "center",
          }}
        />
        <h1 style={{ color: "white", fontSize: "3rem" }}>Ownership</h1>
        <p style={{ color: "white", fontSize: "1.25rem", padding: "0px 30px" }}>
          Ownership details will be provided in the near future, prior to
          launch.
        </p>
      </div>
    </div>
  );
}
